# Generated by Django 4.1.3 on 2022-12-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nutricionistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nut_nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('nut_crn', models.CharField(max_length=255, verbose_name='Crn')),
            ],
            options={
                'verbose_name_plural': 'nutricionistas',
            },
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pac_nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('pac_idade', models.IntegerField(default=1, verbose_name='Idade')),
                ('pac_meta', models.CharField(max_length=255, verbose_name='Meta')),
                ('pac_nut_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nutricionistas')),
            ],
            options={
                'verbose_name_plural': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='cardapios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_cardapio', models.TextField()),
                ('car_nut_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nutricionistas')),
                ('car_pac_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pacientes')),
            ],
            options={
                'verbose_name_plural': 'cardapios dos pacientes',
                'unique_together': {('car_pac_nome', 'car_nut_nome')},
            },
        ),
    ]
