# Generated by Django 4.1.3 on 2022-12-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cardapios',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cardapios',
            name='car_nut_nome',
        ),
    ]
